/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset */
        get: operations["dataset_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset File */
        get: operations["dataset_file_api_dataset_files__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset Archive
         * @description The whole dataset as a zip, with a SHA256SUMS list inside.
         */
        get: operations["dataset_archive_api_dataset_archive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/raw/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Raw */
        get: operations["dataset_raw_api_dataset_raw__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rulepack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rulepack */
        get: operations["rulepack_api_rulepack_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["latest_run_api_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/vintages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fee Vintages */
        get: operations["fee_vintages_api_fees_vintages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/localities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fee Localities */
        get: operations["fee_localities_api_fees_localities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fee Price */
        post: operations["fee_price_api_fees_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BundleSummary */
        BundleSummary: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "notes" | "edi";
            /** Name */
            name: string;
            /** Blurb */
            blurb: string;
            /** Count */
            count: number;
            /** Bytes */
            bytes: number;
        };
        /**
         * Dataset
         * @description The manifest, plus the cohort counts every page needs before any run.
         */
        Dataset: {
            /** Files */
            files: components["schemas"]["FileSummary"][];
            /** Encounters */
            encounters: number;
            /** Study */
            study: number;
            /** Comparator */
            comparator: number;
            /** Codes */
            codes: string[];
            /** Periodstart */
            periodStart: string | null;
            /** Periodend */
            periodEnd: string | null;
            /** Contenthash */
            contentHash: string;
        };
        DeliveredFile: components["schemas"]["TableFile"] | components["schemas"]["NoteBundle"] | components["schemas"]["EdiBundle"];
        /** DeniedLine */
        DeniedLine: {
            /** Cpt */
            cpt: string;
            /** Codes */
            codes: string[];
        };
        /**
         * Derivation
         * @description A priced answer with its arithmetic and its receipts. Mirrors ``worth-fees price --json``.
         */
        Derivation: {
            /** Amount */
            amount: string;
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
            /** Code */
            code: string;
            /** Modifier */
            modifier: string;
            /** Modifiers */
            modifiers: string[];
            /** Locality */
            locality: string;
            /** Localityname */
            localityName: string;
            /** Placeofservice */
            placeOfService: string;
            /** Ruleyear */
            ruleYear: number;
            /** Quarter */
            quarter: number;
            /** Paymentbasis */
            paymentBasis: string;
            inputs: components["schemas"]["DerivationInputs"];
            /** Adjustedrvutotal */
            adjustedRvuTotal: string;
            /** Trace */
            trace: string[];
            source: components["schemas"]["DerivationSource"];
        };
        /**
         * DerivationInputs
         * @description Every input as a decimal string. Strings, because a float is not money.
         */
        DerivationInputs: {
            /** Workrvu */
            workRvu: string;
            /** Pervu */
            peRvu: string;
            /** Mprvu */
            mpRvu: string;
            /** Workgpci */
            workGpci: string;
            /** Pegpci */
            peGpci: string;
            /** Mpgpci */
            mpGpci: string;
            /** Conversionfactor */
            conversionFactor: string;
        };
        /** DerivationSource */
        DerivationSource: {
            /** Release */
            release: string;
            /** Releasedate */
            releaseDate: string;
            /** Files */
            files: components["schemas"]["SourceLink"][];
        };
        /** Distribution */
        Distribution: {
            /** N */
            n: number;
            /** Min */
            min: number;
            /** Q1 */
            q1: number;
            /** Median */
            median: number;
            /** Q3 */
            q3: number;
            /** Max */
            max: number;
        };
        /** EdiBundle */
        EdiBundle: {
            /**
             * Kind
             * @constant
             */
            kind: "edi";
            /** Name */
            name: string;
            /** Blurb */
            blurb: string;
            /** Count */
            count: number;
            /** Bytes */
            bytes: number;
            /** Files */
            files: components["schemas"]["EdiFile"][];
        };
        /** EdiFile */
        EdiFile: {
            /** Name */
            name: string;
            /** Bytes */
            bytes: number;
            /** Claims */
            claims: number;
            /** Lines */
            lines: number;
            /** Segments */
            segments: string[];
        };
        /** Encounter */
        Encounter: {
            /** Id */
            id: string;
            /** Account */
            account: string;
            /** Cpt */
            cpt: string;
            /** Procedures */
            procedures: string[];
            /** Cohort */
            cohort: string;
            /** Specialty */
            specialty: string;
            /** Date */
            date: string;
            /** Payer */
            payer: string;
            /** Score */
            score: number;
            /** Minutes */
            minutes: number;
            /** Realized */
            realized: number;
            /** Realizedclaim */
            realizedClaim: number;
            /** Increasedservice */
            increasedService: boolean;
            /** Scheduleexpected */
            scheduleExpected: number | null;
            /** Expected */
            expected: number | null;
            /** Ratio */
            ratio: number | null;
            pfs: components["schemas"]["PfsAmounts"] | null;
            /** Denied */
            denied: components["schemas"]["DeniedLine"][];
            /** Markers */
            markers: components["schemas"]["MarkerRow"][];
            /** Superseded */
            superseded: components["schemas"]["SupersededMarker"][];
            /** Adequacytrace */
            adequacyTrace: string[];
        };
        FileSummary: components["schemas"]["TableSummary"] | components["schemas"]["BundleSummary"];
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description What this instance is, and what it is pointed at.
         */
        Health: {
            /** Api */
            api: string;
            /** Worthcomplexity */
            worthComplexity: string;
            /** Worthfees */
            worthFees: string;
            rulePack: components["schemas"]["RulePackRef"];
            /** Datasetdir */
            datasetDir: string;
            /** Locality */
            locality: string;
            /** Setting */
            setting: string;
            /** Database */
            database: string;
            /** Fees */
            fees: components["schemas"]["VintageInfo"][];
            /** Latestrun */
            latestRun: boolean;
        };
        /** IndexRecord */
        IndexRecord: {
            /** Code */
            code: string;
            /** Institution */
            institution: string;
            /** Periodstart */
            periodStart: string;
            /** Periodend */
            periodEnd: string;
            /** N */
            n: number;
            distribution: components["schemas"]["Distribution"];
            /** Slopes */
            slopes: components["schemas"]["SlopeStratum"][];
            /** Adequacy */
            adequacy: number | null;
            /** Adequacycilow */
            adequacyCiLow: number | null;
            /** Adequacycihigh */
            adequacyCiHigh: number | null;
            /** Scored */
            scored: number;
            /** Excluded */
            excluded: number;
            /** Locality */
            locality: string;
            /** Setting */
            setting: string;
            /** Referencerelease */
            referenceRelease: string;
            /** Suppressed */
            suppressed: boolean;
            /** Suppressionreason */
            suppressionReason: string | null;
        };
        /** Locality */
        Locality: {
            /** Locality */
            locality: string;
            /** Name */
            name: string;
            /** Mac */
            mac: string;
        };
        /** MarkerRow */
        MarkerRow: {
            /** Id */
            id: string;
            /** Provenance */
            provenance: string;
            /** Value */
            value: number;
            /** Low */
            low: number;
            /** High */
            high: number;
            /** Norm */
            norm: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
            /** Source */
            source: string;
            /** Evidence */
            evidence: string | null;
        };
        /** MarkerRule */
        MarkerRule: {
            /** Id */
            id: string;
            /** Provenance */
            provenance: string;
            /** Weight */
            weight: number;
            /** Anchorlow */
            anchorLow: number;
            /** Anchorhigh */
            anchorHigh: number;
            /** Note */
            note: string | null;
            /** Aggregate */
            aggregate: string;
            /** Notetypes */
            noteTypes: string[];
            /** Sections */
            sections: string[];
            /** Excludedsections */
            excludedSections: string[];
            /** Patterns */
            patterns: components["schemas"]["RulePattern"][];
        };
        /**
         * MultiplierRow
         * @description A payer's multiple of the schedule. Partner-only: never in an index record.
         */
        MultiplierRow: {
            /** Payer */
            payer: string;
            /** N */
            n: number;
            /** Value */
            value: number;
            /** Q1 */
            q1: number;
            /** Q3 */
            q3: number;
        };
        /** NoteBundle */
        NoteBundle: {
            /**
             * Kind
             * @constant
             */
            kind: "notes";
            /** Name */
            name: string;
            /** Blurb */
            blurb: string;
            /** Count */
            count: number;
            /** Bytes */
            bytes: number;
            /** Files */
            files: components["schemas"]["NoteFile"][];
        };
        /** NoteEngine */
        NoteEngine: {
            /** Header */
            header: string;
            /** Negation */
            negation: string;
            /** Historical */
            historical: string;
            /** Terminator */
            terminator: string;
            /** Lookback */
            lookback: number;
        };
        /** NoteFile */
        NoteFile: {
            /** Name */
            name: string;
            /** Encounter */
            encounter: string;
            /** Notetype */
            noteType: string;
            /** Author */
            author: string;
            /** Sha256 */
            sha256: string;
            /** Bytes */
            bytes: number;
            /** Text */
            text: string;
        };
        /**
         * PfsAmounts
         * @description A comparator encounter's fee-schedule amounts, the denominator's inputs.
         */
        PfsAmounts: {
            /** Release */
            release: string;
            /** Amount */
            amount: number;
            /** Referencerelease */
            referenceRelease: string;
            /** Referenceamount */
            referenceAmount: number;
            /** Archivesha256 */
            archiveSha256: string;
        };
        /** PriceRequest */
        PriceRequest: {
            /** Code */
            code: string;
            /** Locality */
            locality: string;
            /**
             * Date
             * @default today
             */
            date: string;
            /**
             * Setting
             * @default non-facility
             * @enum {string}
             */
            setting: "facility" | "non-facility";
            /** Modifiers */
            modifiers?: string[];
            /**
             * Paymentbasis
             * @default non-qualifying-apm
             * @enum {string}
             */
            paymentBasis: "non-qualifying-apm" | "qualifying-apm";
        };
        /** RulePack */
        RulePack: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Status */
            status: string;
            /** Digest */
            digest: string;
            /** Markers */
            markers: components["schemas"]["MarkerRule"][];
        };
        /** RulePackRef */
        RulePackRef: {
            /** Id */
            id: string;
            /** Digest */
            digest: string;
            /** Status */
            status: string;
        };
        /** RulePattern */
        RulePattern: {
            /** Id */
            id: string;
            /** Regex */
            regex: string;
            /** Value */
            value: number | null;
            /** Scale */
            scale: number;
        };
        /** RunMeta */
        RunMeta: {
            /** Package */
            package: string;
            /** Rulepack */
            rulePack: string;
            /** Digest */
            digest: string;
            /** Status */
            status: string;
            /** Filter */
            filter: string;
        };
        /**
         * RunResult
         * @description Everything one run computed. No file contents: those are served separately.
         */
        RunResult: {
            run: components["schemas"]["RunMeta"];
            rulePack: components["schemas"]["RulePack"];
            noteEngine: components["schemas"]["NoteEngine"];
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Records */
            records: components["schemas"]["IndexRecord"][];
            /** Encounters */
            encounters: components["schemas"]["Encounter"][];
            scheduleCurve: components["schemas"]["ScheduleCurve"];
            /** Multipliers */
            multipliers: components["schemas"]["MultiplierRow"][];
            /** Thinpayers */
            thinPayers: string[];
            /** Thinstrata */
            thinStrata: string[];
            summary: components["schemas"]["Summary"];
            /** Timings */
            timings: {
                [key: string]: number;
            };
        };
        /**
         * ScheduleCurve
         * @description The fee schedule's complexity relation, fitted on the comparator cohort.
         *
         *     Medicare PFS dollars against Layer A score, no payer in it.
         */
        ScheduleCurve: {
            /** Id */
            id: string;
            /** N */
            n: number;
            /** Slope */
            slope: number;
            /** Intercept */
            intercept: number;
            /** R2 */
            r2: number;
            /** Xmin */
            xMin: number;
            /** Xmax */
            xMax: number;
            /** Release */
            release: string;
            /** Archivesha256 */
            archiveSha256: string;
            /** Locality */
            locality: string;
            /** Localityname */
            localityName: string;
            /** Setting */
            setting: string;
        };
        /**
         * Scoring
         * @description The formula and the reader, served without a run: the Score tab needs no numbers.
         */
        Scoring: {
            rulePack: components["schemas"]["RulePack"];
            noteEngine: components["schemas"]["NoteEngine"];
        };
        /** SlopeStratum */
        SlopeStratum: {
            /** Payer */
            payer: string;
            /** N */
            n: number;
            /** Slope */
            slope: number;
            /** Cilow */
            ciLow: number;
            /** Cihigh */
            ciHigh: number;
            /** R2 */
            r2: number;
            /** Differentiates */
            differentiates: boolean;
            /** Suppressed */
            suppressed: boolean;
        };
        /** SourceLink */
        SourceLink: {
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /** Role */
            role: string;
            /** Releasedate */
            releaseDate: string;
            /** Note */
            note: string | null;
        };
        /** Step */
        Step: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Result */
            result: string;
            /** Stage */
            stage: string;
        };
        /** Summary */
        Summary: {
            /** Linkagerate */
            linkageRate: number;
            /** Study */
            study: number;
            /** Comparator */
            comparator: number;
            /** Scored */
            scored: number;
            /** Excluded */
            excluded: number;
            /** Codes */
            codes: string[];
            /** Institution */
            institution: string;
            /** Periodstart */
            periodStart: string | null;
            /** Periodend */
            periodEnd: string | null;
            /** Suppressedstrata */
            suppressedStrata: number;
            /** Strata */
            strata: number;
            /** Locality */
            locality: string;
            /** Localityname */
            localityName: string;
            /** Setting */
            setting: string;
            /** Referencerelease */
            referenceRelease: string;
            /** Unmultiplied */
            unmultiplied: number;
        };
        /** SupersededMarker */
        SupersededMarker: {
            /** Id */
            id: string;
            /** Provenance */
            provenance: string;
            /** Value */
            value: number;
            /** Source */
            source: string;
            /** Evidence */
            evidence: string | null;
        };
        /** TableFile */
        TableFile: {
            /**
             * Kind
             * @constant
             */
            kind: "table";
            /** Name */
            name: string;
            /** Blurb */
            blurb: string;
            /** Bytes */
            bytes: number;
            /** Sha256 */
            sha256: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
        };
        /** TableSummary */
        TableSummary: {
            /**
             * Kind
             * @constant
             */
            kind: "table";
            /** Name */
            name: string;
            /** Blurb */
            blurb: string;
            /** Bytes */
            bytes: number;
            /** Sha256 */
            sha256: string;
            /** Rows */
            rows: number;
            /** Columns */
            columns: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VintageInfo */
        VintageInfo: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Ruleyear */
            ruleYear: number;
            /** Quarter */
            quarter: number;
            /** Effectivefrom */
            effectiveFrom: string;
            /** Effectiveto */
            effectiveTo: string;
            /** Releasedon */
            releasedOn: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "database" | "fixture";
            /**
             * Coverage
             * @enum {string}
             */
            coverage: "archive" | "fixture";
            /** Codes */
            codes: number;
            /** Localities */
            localities: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    dataset_api_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
        };
    };
    dataset_file_api_dataset_files__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveredFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_archive_api_dataset_archive_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dataset_raw_api_dataset_raw__path__get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rulepack_api_rulepack_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scoring"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
        };
    };
    latest_run_api_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
        };
    };
    fee_vintages_api_fees_vintages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VintageInfo"][];
                };
            };
        };
    };
    fee_localities_api_fees_localities_get: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Locality"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fee_price_api_fees_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Derivation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
